---
name: Publish to website
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'messages: ${{ toJson(github.event.commits.*.message) }}'"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-versions: 10.x
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: us-west-2
